# Generated by Django 5.1.5 on 2025-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='author',
            field=models.CharField(default='Неизвестный автор', max_length=200, verbose_name='ФИО'),
        ),
    ]
