# Generated by Django 5.1.5 on 2025-02-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('description', models.CharField(max_length=200, verbose_name='Описание фильма')),
                ('movie_review', models.TextField(verbose_name='Отзыв о фильме')),
                ('author', models.CharField(default='Неизвестный автор', max_length=200, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Кинопроект',
                'verbose_name_plural': 'Кинопроекты',
            },
        ),
    ]
