# Generated by Django 5.1.5 on 2025-02-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_post',
            new_name='Reviews_post',
        ),
    ]
